# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'front.ui'
##
## Created by: Qt User Interface Compiler version 6.2.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QFrame, QGridLayout,
    QHBoxLayout, QLabel, QLineEdit, QMainWindow,
    QMenuBar, QPushButton, QSizePolicy, QSpinBox,
    QStatusBar, QTabWidget, QWidget)

class Ui_AlarmsClock(object):
    def setupUi(self, AlarmsClock):
        if not AlarmsClock.objectName():
            AlarmsClock.setObjectName(u"AlarmsClock")
        AlarmsClock.resize(700, 650)
        AlarmsClock.setMinimumSize(QSize(700, 650))
        AlarmsClock.setMaximumSize(QSize(700, 650))
        AlarmsClock.setStyleSheet(u"")
        self.centralwidget = QWidget(AlarmsClock)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(-3, 0, 711, 641))
        self.tabWidget.setStyleSheet(u"background-color: #4D4D4D;")
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.tab.setStyleSheet(u"color: white;")
        self.label = QLabel(self.tab)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(200, 130, 61, 50))
        font = QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.usa_time_label = QLabel(self.tab)
        self.usa_time_label.setObjectName(u"usa_time_label")
        self.usa_time_label.setGeometry(QRect(390, 130, 311, 50))
        font1 = QFont()
        font1.setFamilies([u"Sitka Display"])
        font1.setPointSize(20)
        self.usa_time_label.setFont(font1)
        self.label_2 = QLabel(self.tab)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(200, 240, 131, 50))
        self.label_2.setFont(font)
        self.germany_time_label = QLabel(self.tab)
        self.germany_time_label.setObjectName(u"germany_time_label")
        self.germany_time_label.setGeometry(QRect(390, 240, 311, 50))
        self.germany_time_label.setFont(font)
        self.label_3 = QLabel(self.tab)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(200, 350, 61, 50))
        self.label_3.setFont(font)
        self.iran_time_label = QLabel(self.tab)
        self.iran_time_label.setObjectName(u"iran_time_label")
        self.iran_time_label.setGeometry(QRect(390, 350, 311, 50))
        self.iran_time_label.setFont(font)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.tab_2.setStyleSheet(u"color: white;")
        self.gridLayoutWidget = QWidget(self.tab_2)
        self.gridLayoutWidget.setObjectName(u"gridLayoutWidget")
        self.gridLayoutWidget.setGeometry(QRect(9, 9, 681, 421))
        self.alarms_gl = QGridLayout(self.gridLayoutWidget)
        self.alarms_gl.setObjectName(u"alarms_gl")
        self.alarms_gl.setContentsMargins(0, 0, 0, 0)
        self.new_alarm_le = QLineEdit(self.tab_2)
        self.new_alarm_le.setObjectName(u"new_alarm_le")
        self.new_alarm_le.setGeometry(QRect(12, 460, 201, 31))
        self.new_alarm_hour = QSpinBox(self.tab_2)
        self.new_alarm_hour.setObjectName(u"new_alarm_hour")
        self.new_alarm_hour.setGeometry(QRect(232, 470, 42, 20))
        self.new_alarm_hour.setMaximum(23)
        self.new_alarm_minute = QSpinBox(self.tab_2)
        self.new_alarm_minute.setObjectName(u"new_alarm_minute")
        self.new_alarm_minute.setGeometry(QRect(302, 470, 42, 22))
        self.new_alarm_minute.setMaximum(59)
        self.add_alarm_btn = QPushButton(self.tab_2)
        self.add_alarm_btn.setObjectName(u"add_alarm_btn")
        self.add_alarm_btn.setGeometry(QRect(301, 550, 75, 24))
        font2 = QFont()
        font2.setPointSize(13)
        self.add_alarm_btn.setFont(font2)
        self.add_alarm_btn.setCursor(QCursor(Qt.PointingHandCursor))
        self.add_alarm_btn.setStyleSheet(u"border-radius: 6px;\n"
"background-color: #262626;")
        self.label_4 = QLabel(self.tab_2)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(242, 450, 49, 16))
        self.label_5 = QLabel(self.tab_2)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(303, 450, 49, 16))
        self.horizontalLayoutWidget = QWidget(self.tab_2)
        self.horizontalLayoutWidget.setObjectName(u"horizontalLayoutWidget")
        self.horizontalLayoutWidget.setGeometry(QRect(12, 500, 681, 41))
        self.horizontalLayout = QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.sun_cb = QCheckBox(self.horizontalLayoutWidget)
        self.sun_cb.setObjectName(u"sun_cb")

        self.horizontalLayout.addWidget(self.sun_cb)

        self.mon_cb = QCheckBox(self.horizontalLayoutWidget)
        self.mon_cb.setObjectName(u"mon_cb")

        self.horizontalLayout.addWidget(self.mon_cb)

        self.tue_cb = QCheckBox(self.horizontalLayoutWidget)
        self.tue_cb.setObjectName(u"tue_cb")

        self.horizontalLayout.addWidget(self.tue_cb)

        self.wed_cb = QCheckBox(self.horizontalLayoutWidget)
        self.wed_cb.setObjectName(u"wed_cb")

        self.horizontalLayout.addWidget(self.wed_cb)

        self.thu_cb = QCheckBox(self.horizontalLayoutWidget)
        self.thu_cb.setObjectName(u"thu_cb")

        self.horizontalLayout.addWidget(self.thu_cb)

        self.fri_cb = QCheckBox(self.horizontalLayoutWidget)
        self.fri_cb.setObjectName(u"fri_cb")

        self.horizontalLayout.addWidget(self.fri_cb)

        self.sat_cb = QCheckBox(self.horizontalLayoutWidget)
        self.sat_cb.setObjectName(u"sat_cb")

        self.horizontalLayout.addWidget(self.sat_cb)

        self.line = QFrame(self.tab_2)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(10, 430, 681, 20))
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.tab_3.setStyleSheet(u"color: white;")
        self.stopwatch_stop_btn = QPushButton(self.tab_3)
        self.stopwatch_stop_btn.setObjectName(u"stopwatch_stop_btn")
        self.stopwatch_stop_btn.setGeometry(QRect(400, 320, 75, 24))
        self.stopwatch_stop_btn.setCursor(QCursor(Qt.PointingHandCursor))
        self.stopwatch_stop_btn.setStyleSheet(u"border-radius: 6px;\n"
"background-color: #262626;")
        self.stopwatch_start_btn = QPushButton(self.tab_3)
        self.stopwatch_start_btn.setObjectName(u"stopwatch_start_btn")
        self.stopwatch_start_btn.setGeometry(QRect(200, 320, 75, 24))
        self.stopwatch_start_btn.setCursor(QCursor(Qt.PointingHandCursor))
        self.stopwatch_start_btn.setStyleSheet(u"border-radius: 6px;\n"
"background-color: #262626;")
        self.stopwatch_label = QLabel(self.tab_3)
        self.stopwatch_label.setObjectName(u"stopwatch_label")
        self.stopwatch_label.setGeometry(QRect(100, 210, 481, 41))
        self.stopwatch_label.setFont(font)
        self.stopwatch_label.setStyleSheet(u"")
        self.stopwatch_label.setAlignment(Qt.AlignCenter)
        self.stopwatch_reset_btn = QPushButton(self.tab_3)
        self.stopwatch_reset_btn.setObjectName(u"stopwatch_reset_btn")
        self.stopwatch_reset_btn.setGeometry(QRect(300, 320, 75, 24))
        self.stopwatch_reset_btn.setCursor(QCursor(Qt.PointingHandCursor))
        self.stopwatch_reset_btn.setStyleSheet(u"border-radius: 6px;\n"
"background-color: #262626;")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.tab_4.setStyleSheet(u"color: white;")
        self.timer_hour_tb = QLineEdit(self.tab_4)
        self.timer_hour_tb.setObjectName(u"timer_hour_tb")
        self.timer_hour_tb.setGeometry(QRect(230, 180, 61, 71))
        font3 = QFont()
        font3.setPointSize(27)
        self.timer_hour_tb.setFont(font3)
        self.timer_hour_tb.setAlignment(Qt.AlignCenter)
        self.timer_minute_tb = QLineEdit(self.tab_4)
        self.timer_minute_tb.setObjectName(u"timer_minute_tb")
        self.timer_minute_tb.setGeometry(QRect(310, 180, 61, 71))
        self.timer_minute_tb.setFont(font3)
        self.timer_minute_tb.setAlignment(Qt.AlignCenter)
        self.timer_second_tb = QLineEdit(self.tab_4)
        self.timer_second_tb.setObjectName(u"timer_second_tb")
        self.timer_second_tb.setGeometry(QRect(390, 180, 61, 71))
        self.timer_second_tb.setFont(font3)
        self.timer_second_tb.setAlignment(Qt.AlignCenter)
        self.timer_stop_btn = QPushButton(self.tab_4)
        self.timer_stop_btn.setObjectName(u"timer_stop_btn")
        self.timer_stop_btn.setGeometry(QRect(410, 320, 75, 24))
        self.timer_stop_btn.setCursor(QCursor(Qt.PointingHandCursor))
        self.timer_stop_btn.setStyleSheet(u"border-radius: 6px;\n"
"background-color: #262626;")
        self.timer_start_btn = QPushButton(self.tab_4)
        self.timer_start_btn.setObjectName(u"timer_start_btn")
        self.timer_start_btn.setGeometry(QRect(190, 320, 75, 24))
        self.timer_start_btn.setCursor(QCursor(Qt.PointingHandCursor))
        self.timer_start_btn.setStyleSheet(u"border-radius: 6px;\n"
"background-color: #262626;")
        self.timer_reset_btn = QPushButton(self.tab_4)
        self.timer_reset_btn.setObjectName(u"timer_reset_btn")
        self.timer_reset_btn.setGeometry(QRect(300, 320, 75, 24))
        self.timer_reset_btn.setCursor(QCursor(Qt.PointingHandCursor))
        self.timer_reset_btn.setStyleSheet(u"border-radius: 6px;\n"
"background-color: #262626;")
        self.tabWidget.addTab(self.tab_4, "")
        AlarmsClock.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(AlarmsClock)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 700, 22))
        AlarmsClock.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(AlarmsClock)
        self.statusbar.setObjectName(u"statusbar")
        AlarmsClock.setStatusBar(self.statusbar)

        self.retranslateUi(AlarmsClock)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(AlarmsClock)
    # setupUi

    def retranslateUi(self, AlarmsClock):
        AlarmsClock.setWindowTitle(QCoreApplication.translate("AlarmsClock", u"Alarms & Clock", None))
        self.label.setText(QCoreApplication.translate("AlarmsClock", u"USA", None))
        self.usa_time_label.setText(QCoreApplication.translate("AlarmsClock", u"00", None))
        self.label_2.setText(QCoreApplication.translate("AlarmsClock", u"GERMANY", None))
        self.germany_time_label.setText(QCoreApplication.translate("AlarmsClock", u"00", None))
        self.label_3.setText(QCoreApplication.translate("AlarmsClock", u"IRAN", None))
        self.iran_time_label.setText(QCoreApplication.translate("AlarmsClock", u"00", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("AlarmsClock", u"World Clock", None))
        self.new_alarm_le.setPlaceholderText(QCoreApplication.translate("AlarmsClock", u"alarm title...", None))
        self.add_alarm_btn.setText(QCoreApplication.translate("AlarmsClock", u"+", None))
        self.label_4.setText(QCoreApplication.translate("AlarmsClock", u"hour", None))
        self.label_5.setText(QCoreApplication.translate("AlarmsClock", u"minute", None))
        self.sun_cb.setText(QCoreApplication.translate("AlarmsClock", u"Sun", None))
        self.mon_cb.setText(QCoreApplication.translate("AlarmsClock", u"Mon", None))
        self.tue_cb.setText(QCoreApplication.translate("AlarmsClock", u"Tue", None))
        self.wed_cb.setText(QCoreApplication.translate("AlarmsClock", u"Wed", None))
        self.thu_cb.setText(QCoreApplication.translate("AlarmsClock", u"Thu", None))
        self.fri_cb.setText(QCoreApplication.translate("AlarmsClock", u"Fri", None))
        self.sat_cb.setText(QCoreApplication.translate("AlarmsClock", u"Sat", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("AlarmsClock", u"Alarm", None))
        self.stopwatch_stop_btn.setText(QCoreApplication.translate("AlarmsClock", u"Stop", None))
        self.stopwatch_start_btn.setText(QCoreApplication.translate("AlarmsClock", u"Start", None))
        self.stopwatch_label.setText(QCoreApplication.translate("AlarmsClock", u"0:0:0", None))
        self.stopwatch_reset_btn.setText(QCoreApplication.translate("AlarmsClock", u"Reset", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("AlarmsClock", u"StopWatch", None))
        self.timer_hour_tb.setText(QCoreApplication.translate("AlarmsClock", u"0", None))
        self.timer_minute_tb.setText(QCoreApplication.translate("AlarmsClock", u"15", None))
        self.timer_second_tb.setText(QCoreApplication.translate("AlarmsClock", u"30", None))
        self.timer_stop_btn.setText(QCoreApplication.translate("AlarmsClock", u"Stop", None))
        self.timer_start_btn.setText(QCoreApplication.translate("AlarmsClock", u"Start", None))
        self.timer_reset_btn.setText(QCoreApplication.translate("AlarmsClock", u"Reset", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QCoreApplication.translate("AlarmsClock", u"Timer", None))
    # retranslateUi

